MMCREvents.server(event => {

    const api = event.getAPI()
    const structure = event.createStructure("mmcr_kubejs:distillation_column")

    structure

        .mainStructure(stage =>
            stage
                .pattern("ABX", "XBX", "XBX")
                .pattern("AXX", "X X", "XXX")
                .pattern("DEC", "XXX", "XXX")
                .set('X', api.block('minecraft:iron_block'))
                .set('A', api.anyOfEnergyInput())
                .set('B', api.anyOfFluidOutput())
                .set('D', api.anyOfFluidInput())
                .set('C', api.anyOfItemOutput())
                .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )
        .expandStructure(stage => stage
            .pattern("ABX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX", "XBX")
            .pattern("AXX", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "X X", "XXX")
            .pattern("DEC", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX", "XXX")
            .set('X', api.block('minecraft:iron_block'))
            .set('A', api.anyOfEnergyInput())
            .set('B', api.anyOfFluidOutput())
            .set('D', api.anyOfFluidInput())
            .set('C', api.anyOfItemOutput())
            .controller('E')
        )

    structure.build()

})
